---

- name: Ensure Kong DB database
  postgresql_db:
    name: "{{ kong.db.name }}"
    state: present
    login_host: "{{ kong.db.host }}"
    login_user: "{{ kong.db.root_user }}"
    login_password: "{{ kong.db.root_password }}"
  register: create_db
  when: kong.db.root_user and kong.db.root_password

- name: Ensure Kong DB user
  postgresql_user:
    db: "{{ kong.db.name }}"
    login_host: "{{ kong.db.host }}"
    login_password: "{{ kong.db.root_password }}"
    login_user: "{{ kong.db.root_user }}"
    name: "{{ kong.db.user }}"
    password: "{{ kong.db.password }}"
    priv: "ALL"
    state: present
  when: kong.db.root_user and kong.db.root_password and create_db.changed

- name: Write kong nginx config
  become: yes
  template:
    dest: /etc/kong/default_nginx.template
    group: root
    mode: 0644
    owner: root
    src: default_nginx.template.j2
  notify:
    - restart kong

- name: Write kong config
  become: yes
  template:
    dest: /etc/kong/kong.conf
    group: root
    mode: 0644
    owner: root
    src: kong.conf.j2
  notify:
    - restart kong

- name: Flush handlers to ensure everything is up to date
  meta: flush_handlers

- name: Ensure Kong is running
  become: yes
  service:
    name: kong
    state: started
