---

- name: Install Kong Dependencies
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ sansible_kong_dependencies }}"

- name: Add BinTray deb repository
  become: yes
  apt_repository:
    repo: "deb https://dl.bintray.com/mashape/kong-ubuntu-{{ ansible_distribution_release }}-{{ sansible_kong_version | regex_replace('(^[0-9]+\\.[0-9]+).*$', '\\1.x') }}
      {{ ansible_distribution_release }} main"
    state: present

- name: "Install Kong {{ sansible_kong_version }}"
  become: yes
  apt:
    name: "kong={{ sansible_kong_version }}"
    force: yes  # https://github.com/Kong/kong/issues/1728

- name: Ensure log directory owned by nginx user
  become: yes
  file:
    path: /usr/local/kong/logs
    state: directory
    owner: www-data
    group: www-data

- name: Create kong init.d script
  become: yes
  template:
    dest: /etc/init.d/kong
    mode: 0750
    src: initd.j2

- name: Ensure kong service is enabled
  become: yes
  service:
    name: kong
    enabled: yes
